// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text.Json.Nodes;
using Microsoft.Extensions.AI;
using Microsoft.Teams.Bot.Apps;
using Microsoft.Teams.Bot.Apps.Handlers;
using Microsoft.Teams.Bot.Apps.Schema;
using OpenAI;

WebApplicationBuilder builder = WebApplication.CreateSlimBuilder(args);
builder.Services.AddTeamsBotApplication();

string apiKey = builder.Configuration["OpenAI:ApiKey"] ?? throw new InvalidOperationException("OpenAI:ApiKey is required.");
string modelId = builder.Configuration["OpenAI:ModelId"] ?? throw new InvalidOperationException("OpenAI:ModelId is required.");

IChatClient chatClient = new OpenAIClient(apiKey)
    .GetChatClient(modelId)
    .AsIChatClient();

WebApplication webApp = builder.Build();
TeamsBotApplication teamsApp = webApp.UseTeamsBotApplication();

teamsApp.OnMessage(async (context, cancellationToken) =>
{
    TeamsStreamingWriter writer = context.GetStreamingWriter();
    await writer.SendInformativeUpdateAsync("Thinking…", cancellationToken);

    string userText = context.Activity.Text ?? "Tell me something interesting.";

    await foreach (ChatResponseUpdate update in chatClient.GetStreamingResponseAsync(
        [new ChatMessage(ChatRole.User, userText)],
        cancellationToken: cancellationToken))
    {
        if (!string.IsNullOrEmpty(update.Text))
            await writer.AppendResponseAsync(update.Text, cancellationToken);
    }

    await writer.AppendResponseAsync(" [1]", cancellationToken);

    CitationEntity citation = new()
    {
        Citation =
        [
            new CitationClaim
            {
                Position = 1,
                Appearance = new CitationAppearance
                {
                    Name     = "OpenAI " + modelId,
                    Abstract = "Response generated by " + modelId + " via the OpenAI API.",
                    Url      = new Uri("https://platform.openai.com/docs/models"),
                    Icon     = CitationIcon.Text,
                }.ToDocument()
            }
        ]
    };

    TeamsAttachment card = TeamsAttachment.CreateBuilder()
        .WithAdaptiveCard(new JsonObject
        {
            ["type"] = "AdaptiveCard",
            ["version"] = "1.5",
            ["body"] = new JsonArray
            {
                new JsonObject
                {
                    ["type"] = "TextBlock",
                    ["text"] = "Response generated by " + modelId,
                    ["wrap"] = true,
                }
            }
        })
        .Build();

    await writer.FinalizeResponseAsync(attachments: [card], entities: [citation], cancellationToken);
});

webApp.Run();
