// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text.Json;
using System.ClientModel;
using Azure.AI.OpenAI;
using Microsoft.Extensions.AI;
using Microsoft.Teams.Apps;
using Microsoft.Teams.Cards;

using Microsoft.Teams.Apps.Schema;
using Microsoft.Teams.Apps.Schema.Entities;

WebApplicationBuilder builder = WebApplication.CreateSlimBuilder(args);
builder.Services.AddTeamsBotApplication();

string endpoint = builder.Configuration["AZURE_OPENAI_ENDPOINT"] ?? throw new InvalidOperationException("AzureOpenAI:Endpoint is required.");
string apiKey = builder.Configuration["AZURE_OPENAI_KEY"] ?? throw new InvalidOperationException("AzureOpenAI:ApiKey is required.");
string deployment = builder.Configuration["AZURE_OPENAI_DEPLOYMENT"] ?? throw new InvalidOperationException("AzureOpenAI:Deployment is required.");

builder.Services.AddSingleton<AzureOpenAIClient>(_ => new AzureOpenAIClient(new Uri(endpoint), new ApiKeyCredential(apiKey)));
builder.Services.AddSingleton<IChatClient>(sp =>
    sp.GetRequiredService<AzureOpenAIClient>()
      .GetChatClient(deployment)
      .AsIChatClient());

WebApplication webApp = builder.Build();
TeamsBotApplication teamsApp = webApp.UseTeamsBotApplication();
IChatClient chatClient = webApp.Services.GetRequiredService<IChatClient>();

teamsApp.OnMessage(async (context, cancellationToken) =>
{
    TeamsStreamingWriter writer = TeamsStreamingWriter.CreateFromContext(context);

    // Send "multi-stream" to demo reusing the same writer for a second streamed message
    // after FinalizeResponseAsync (stream reuse). This path does not call OpenAI.
    if ((context.Activity.Text ?? string.Empty).Replace("-", " ").Contains("multi stream", StringComparison.OrdinalIgnoreCase))
    {
        await RunMultiStreamDemoAsync(writer, cancellationToken);
        return;
    }

    await writer.SendInformativeUpdateAsync("Thinking…", cancellationToken);
    await Task.Delay(500, cancellationToken);
    await writer.SendInformativeUpdateAsync("Thinking again !!!", cancellationToken);

    string userText = context.Activity.Text ?? "Tell me something interesting.";

    await foreach (ChatResponseUpdate update in chatClient.GetStreamingResponseAsync(
        [new ChatMessage(ChatRole.User, userText)],
        cancellationToken: cancellationToken))
    {
        if (!string.IsNullOrEmpty(update.Text))
            await writer.AppendResponseAsync(update.Text, cancellationToken);
    }

    await writer.AppendResponseAsync(" [1]", cancellationToken);

    CitationEntity citation = new()
    {
        AdditionalType = ["AIGeneratedContent"],
        Citation =
        [
            new CitationClaim
            {
                Position = 1,
                Appearance = new CitationAppearance
                {
                    Name     = "AzureOpenAI " + deployment,
                    Abstract = "Response generated by " + deployment ,
                    Url      = new Uri("https://platform.openai.com/docs/models"),
                    Icon     = CitationIcons.Text,
                }.ToDocument()
            }
        ]
    };

    TeamsAttachment card = TeamsAttachment.CreateBuilder()
        .WithAdaptiveCard(CreateResponseCard(deployment))
        .Build();

    MessageActivityInput final = new MessageActivityInput()
        .AddAttachment(card)
        .AddEntity(citation)
        .AddFeedback(FeedbackTypes.Custom)
        ;

    await writer.FinalizeResponseAsync(final, cancellationToken);
});

teamsApp.OnMessageSubmitAction(async (context, cancellationToken) =>
{
    await context.SendAsync("You submitted an action with name and value:" + context.Activity.Value?.ActionName + " - " + context.Activity.Value?.ActionValue, cancellationToken);

    return new InvokeResponse(200);
});

static async Task RunMultiStreamDemoAsync(TeamsStreamingWriter writer, CancellationToken cancellationToken)
{
    string[] firstStreamMessages =
    [
        "[stream 1] Starting the first streamed response. ",
        "[stream 1] This is using the default writer instance. ",
        "[stream 1] Next the handler will finalize the current streamed message.",
    ];

    string[] secondStreamMessages =
    [
        "[stream 2] Reusing the writer after finalize reopens the stream. ",
        "[stream 2] This should render after stream 1's final Adaptive Card message. ",
        "[stream 2] The handler finalizes this stream at the end.",
    ];

    // Stream 1: informative placeholder, streamed text chunks, then an Adaptive Card
    // carried on the final message.
    await writer.SendInformativeUpdateAsync("Starting stream 1...", cancellationToken);
    await Task.Delay(1000, cancellationToken);

    foreach (string message in firstStreamMessages)
    {
        await Task.Delay(500, cancellationToken);
        await writer.AppendResponseAsync(message, cancellationToken);
    }

    await writer.AppendResponseAsync("Adaptive Card emitted as part of stream 1.", cancellationToken);

    // A null Text lets the writer fill in the accumulated streamed text; the attachment
    // rides along on the final message.
    MessageActivityInput stream1Final = new MessageActivityInput().AddAttachment(CreateSimpleCard());
    await writer.FinalizeResponseAsync(stream1Final, cancellationToken);

    await Task.Delay(2000, cancellationToken);

    // Stream 2: reuse the same writer after finalize — the informative update reopens the stream.
    await writer.SendInformativeUpdateAsync("Starting stream 2...", cancellationToken);
    await Task.Delay(1000, cancellationToken);

    foreach (string message in secondStreamMessages)
    {
        await Task.Delay(500, cancellationToken);
        await writer.AppendResponseAsync(message, cancellationToken);
    }

    await writer.FinalizeResponseAsync(cancellationToken: cancellationToken);
}

static TeamsAttachment CreateSimpleCard()
{
    AdaptiveCard card = new([
        new TextBlock("Simple Adaptive Card")
        {
            Weight = TextWeight.Bolder,
            Size = TextSize.Large,
            Wrap = true
        },
        new TextBlock("If you can see this card, basic Adaptive Card delivery is working.")
        {
            Wrap = true
        }])
    {
        Version = Microsoft.Teams.Cards.Version.Version1_5
    };

    return TeamsAttachment.CreateBuilder()
        .WithAdaptiveCard(JsonSerializer.SerializeToElement(card))
        .Build();
}

static JsonElement CreateResponseCard(string deployment)
{
    AdaptiveCard card = new([
        new TextBlock("Response generated by " + deployment)
        {
            Wrap = true
        }])
    {
        Version = Microsoft.Teams.Cards.Version.Version1_5
    };

    return JsonSerializer.SerializeToElement(card);
}

webApp.Run();
