// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.ClientModel;
using System.Text.Json;
using Azure.AI.OpenAI;
using Microsoft.Extensions.AI;
using Microsoft.Teams.Apps;
using Microsoft.Teams.Apps.Schema;
using Microsoft.Teams.Apps.Schema.Entities;
using Microsoft.Teams.Cards;

WebApplicationBuilder builder = WebApplication.CreateSlimBuilder(args);
builder.Services.AddTeamsBotApplication();

// Azure OpenAI is optional. When all three settings are present the default message path streams
// live model output; otherwise it falls back to a canned streamed response so the sample still runs.
string? endpoint = builder.Configuration["AzureOpenAI:Endpoint"];
string? apiKey = builder.Configuration["AzureOpenAI:ApiKey"];
string? deployment = builder.Configuration["AzureOpenAI:Deployment"];
bool aiConfigured = !string.IsNullOrWhiteSpace(endpoint)
    && !string.IsNullOrWhiteSpace(apiKey)
    && !string.IsNullOrWhiteSpace(deployment);

if (aiConfigured)
{
    builder.Services.AddSingleton<AzureOpenAIClient>(_ => new AzureOpenAIClient(new Uri(endpoint!), new ApiKeyCredential(apiKey!)));
    builder.Services.AddSingleton<IChatClient>(sp =>
        sp.GetRequiredService<AzureOpenAIClient>()
          .GetChatClient(deployment!)
          .AsIChatClient());
}

WebApplication webApp = builder.Build();
TeamsBotApplication teamsApp = webApp.UseTeamsBotApplication();
IChatClient? chatClient = webApp.Services.GetService<IChatClient>();

teamsApp.OnMessage(async (context, cancellationToken) =>
{
    TeamsStreamingWriter writer = TeamsStreamingWriter.CreateFromContext(context);

    string normalized = (context.Activity.Text ?? string.Empty).Replace("-", " ");

    // "multi stream": reuse the same writer for a second streamed message after finalize.
    if (normalized.Contains("multi stream", StringComparison.OrdinalIgnoreCase))
    {
        await RunMultiStreamDemoAsync(writer, cancellationToken);
        return;
    }

    // "extended markdown": stream content that only renders correctly under extended markdown.
    if (normalized.Contains("extended markdown", StringComparison.OrdinalIgnoreCase))
    {
        await RunExtendedMarkdownDemoAsync(writer, cancellationToken);
        return;
    }

    // Default path: stream live model output when Azure OpenAI is configured, otherwise a
    // canned streamed response so the sample works without any AI backend.
    if (chatClient is null)
    {
        await RunCannedResponseAsync(writer, cancellationToken);
        return;
    }

    await writer.SendInformativeUpdateAsync("Thinking…", cancellationToken);
    await Task.Delay(500, cancellationToken);
    await writer.SendInformativeUpdateAsync("Thinking again !!!", cancellationToken);

    string userText = context.Activity.Text ?? "Tell me something interesting.";

    await foreach (ChatResponseUpdate update in chatClient.GetStreamingResponseAsync(
        [new ChatMessage(ChatRole.User, userText)],
        cancellationToken: cancellationToken))
    {
        if (!string.IsNullOrEmpty(update.Text))
            await writer.AppendResponseAsync(update.Text, cancellationToken);
    }

    await writer.AppendResponseAsync(" [1]", cancellationToken);

    CitationEntity citation = new()
    {
        AdditionalType = ["AIGeneratedContent"],
        Citation =
        [
            new CitationClaim
            {
                Position = 1,
                Appearance = new CitationAppearance
                {
                    Name     = "AzureOpenAI " + deployment,
                    Abstract = "Response generated by " + deployment ,
                    Url      = new Uri("https://platform.openai.com/docs/models"),
                    Icon     = CitationIcons.Text,
                }.ToDocument()
            }
        ]
    };

    TeamsAttachment card = TeamsAttachment.CreateBuilder()
        .WithAdaptiveCard(CreateResponseCard(deployment!))
        .Build();

    MessageActivityInput final = new MessageActivityInput()
        .AddAttachment(card)
        .AddEntity(citation)
        .AddFeedback(FeedbackTypes.Custom)
        ;

    await writer.FinalizeResponseAsync(final, cancellationToken);
});

teamsApp.OnMessageSubmitAction(async (context, cancellationToken) =>
{
    await context.SendAsync("You submitted an action with name and value:" + context.Activity.Value?.ActionName + " - " + context.Activity.Value?.ActionValue, cancellationToken);

    return new InvokeResponse(200);
});

static async Task RunCannedResponseAsync(TeamsStreamingWriter writer, CancellationToken cancellationToken)
{
    string[] messages =
    [
        "Azure OpenAI isn't configured, so here's a canned streamed reply. ",
        "Set AzureOpenAI:Endpoint, :ApiKey, and :Deployment to stream live model output instead. ",
        "You can also try `extended markdown`, `extended markdown before`, or `multi stream`.",
    ];

    await writer.SendInformativeUpdateAsync("Thinking…", cancellationToken);
    await Task.Delay(500, cancellationToken);

    foreach (string message in messages)
    {
        await Task.Delay(500, cancellationToken);
        await writer.AppendResponseAsync(message, cancellationToken);
    }

    await writer.FinalizeResponseAsync(cancellationToken: cancellationToken);
}

static async Task RunMultiStreamDemoAsync(TeamsStreamingWriter writer, CancellationToken cancellationToken)
{
    string[] firstStreamMessages =
    [
        "[stream 1] Starting the first streamed response. ",
        "[stream 1] This is using the default writer instance. ",
        "[stream 1] Next the handler will finalize the current streamed message.",
    ];

    string[] secondStreamMessages =
    [
        "[stream 2] Reusing the writer after finalize reopens the stream. ",
        "[stream 2] This should render after stream 1's final Adaptive Card message. ",
        "[stream 2] The handler finalizes this stream at the end.",
    ];

    // Stream 1: informative placeholder, streamed text chunks, then an Adaptive Card
    // carried on the final message.
    await writer.SendInformativeUpdateAsync("Starting stream 1...", cancellationToken);
    await Task.Delay(1000, cancellationToken);

    foreach (string message in firstStreamMessages)
    {
        await Task.Delay(500, cancellationToken);
        await writer.AppendResponseAsync(message, cancellationToken);
    }

    await writer.AppendResponseAsync("Adaptive Card emitted as part of stream 1.", cancellationToken);

    // A null Text lets the writer fill in the accumulated streamed text; the attachment
    // rides along on the final message.
    MessageActivityInput stream1Final = new MessageActivityInput().AddAttachment(CreateSimpleCard());
    await writer.FinalizeResponseAsync(stream1Final, cancellationToken);

    await Task.Delay(2000, cancellationToken);

    // Stream 2: reuse the same writer after finalize — the informative update reopens the stream.
    await writer.SendInformativeUpdateAsync("Starting stream 2...", cancellationToken);
    await Task.Delay(1000, cancellationToken);

    foreach (string message in secondStreamMessages)
    {
        await Task.Delay(500, cancellationToken);
        await writer.AppendResponseAsync(message, cancellationToken);
    }

    await writer.FinalizeResponseAsync(cancellationToken: cancellationToken);
}

static async Task RunExtendedMarkdownDemoAsync(TeamsStreamingWriter writer, CancellationToken cancellationToken)
{
    // Task lists ("- [x]") and strikethrough ("~~...~~") only render under extended markdown.
    string[] messages =
    [
        "**Extended markdown stream** — rendering features plain markdown can't:\n\n",
        "- [x] Sent with `textFormat: 'extendedmarkdown'`\n",
        "- [x] Task list items render as real checkboxes\n",
        "- [ ] ~~Under plain markdown these would be literal `[ ]` text~~\n",
        "- [x] Strikethrough renders too\n",
    ];

#pragma warning disable ExperimentalTeamsExtendedMarkdown
    // The informative update carries its own format (plain markdown here); the streamed chunks
    // set extended markdown per-chunk via MessageActivityInput, which also formats the final message.
    await writer.SendInformativeUpdateAsync("Starting the *extended* markdown stream…", TextFormats.Markdown, cancellationToken);
    await Task.Delay(1000, cancellationToken);

    foreach (string message in messages)
    {
        await Task.Delay(500, cancellationToken);
        await writer.AppendResponseAsync(new MessageActivityInput().WithText(message, TextFormats.ExtendedMarkdown), cancellationToken);
    }
#pragma warning restore ExperimentalTeamsExtendedMarkdown

    await writer.FinalizeResponseAsync(cancellationToken: cancellationToken);
}

static TeamsAttachment CreateSimpleCard()
{
    AdaptiveCard card = new([
        new TextBlock("Simple Adaptive Card")
        {
            Weight = TextWeight.Bolder,
            Size = TextSize.Large,
            Wrap = true
        },
        new TextBlock("If you can see this card, basic Adaptive Card delivery is working.")
        {
            Wrap = true
        }])
    {
        Version = Microsoft.Teams.Cards.Version.Version1_5
    };

    return TeamsAttachment.CreateBuilder()
        .WithAdaptiveCard(JsonSerializer.SerializeToElement(card))
        .Build();
}

static JsonElement CreateResponseCard(string deployment)
{
    AdaptiveCard card = new([
        new TextBlock("Response generated by " + deployment)
        {
            Wrap = true
        }])
    {
        Version = Microsoft.Teams.Cards.Version.Version1_5
    };

    return JsonSerializer.SerializeToElement(card);
}

webApp.Run();
